version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: prabandh_postgres
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWD}
      POSTGRES_DB: prabandh_pg
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - prabandh_pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: prabandh_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    ports:
      - ${PORT_OLLAMA}:11434
    volumes:
      - ${DATA}/ollama:/root/.ollama
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: serve
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

volumes:
  prabandh_pg_data:
    driver: local