services:
  db:
    image: postgres:latest
    container_name: prabandh_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - prabandh_pg_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - ${PORT_OLLAMA}:11434
    volumes:
      - ${DATA}/ollama:/root/.ollama
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      OLLAMA_MODELS: "gemma:2b"
    command: serve
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

volumes:
  prabandh_pg_data:
    driver: local
